# Generated by Django 4.2.7 on 2023-11-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_result_semester_alter_result_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.BigIntegerField(verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(verbose_name='credits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(max_length=4, null=True, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='semresult',
            name='SGPA',
            field=models.FloatField(verbose_name='SGPA'),
        ),
        migrations.AlterField(
            model_name='semresult',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=10, verbose_name='reg_no'),
        ),
        migrations.DeleteModel(
            name='CourseSemester',
        ),
    ]
