# Generated by Django 4.2.7 on 2023-11-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='semresult',
            name='SGPA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=10),
        ),
    ]
